package com.syb.baiduaip.bean;

import java.util.ArrayList;
import java.util.List;

public class Landmark150 {
    private Landmark cheek_right_1;
    private Landmark cheek_right_3;
    private Landmark cheek_right_5;
    private Landmark cheek_right_7;
    private Landmark cheek_right_9;
    private Landmark cheek_right_11;
    private Landmark chin_2;
    private Landmark cheek_left_11;
    private Landmark cheek_left_9;
    private Landmark cheek_left_7;
    private Landmark cheek_left_5;
    private Landmark cheek_left_3;
    private Landmark cheek_left_1;
    private Landmark eye_right_corner_right;
    private Landmark eye_right_eyelid_upper_2;
    private Landmark eye_right_eyelid_upper_4;
    private Landmark eye_right_eyelid_upper_6;
    private Landmark eye_right_corner_left;
    private Landmark eye_right_eyelid_lower_6;
    private Landmark eye_right_eyelid_lower_4;
    private Landmark eye_right_eyelid_lower_2;
    private Landmark eye_right_eyeball_center;
    private Landmark eyebrow_right_corner_right;
    private Landmark eyebrow_right_upper_2;
    private Landmark eyebrow_right_upper_3;
    private Landmark eyebrow_right_upper_4;
    private Landmark eyebrow_right_corner_left;
    private Landmark eyebrow_right_lower_3;
    private Landmark eyebrow_right_lower_2;
    private Landmark eyebrow_right_lower_1;
    private Landmark eye_left_corner_right;
    private Landmark eye_left_eyelid_upper_2;
    private Landmark eye_left_eyelid_upper_4;
    private Landmark eye_left_eyelid_upper_6;
    private Landmark eye_left_corner_left;
    private Landmark eye_left_eyelid_lower_6;
    private Landmark eye_left_eyelid_lower_4;
    private Landmark eye_left_eyelid_lower_2;
    private Landmark eye_left_eyeball_center;
    private Landmark eyebrow_left_corner_right;
    private Landmark eyebrow_left_upper_2;
    private Landmark eyebrow_left_upper_3;
    private Landmark eyebrow_left_upper_4;
    private Landmark eyebrow_left_corner_left;
    private Landmark eyebrow_left_lower_3;
    private Landmark eyebrow_left_lower_2;
    private Landmark eyebrow_left_lower_1;
    private Landmark nose_right_contour_1;
    private Landmark nose_right_contour_2;
    private Landmark nose_right_contour_3;
    private Landmark nose_right_contour_4;
    private Landmark nose_right_contour_6;
    private Landmark nose_left_contour_6;
    private Landmark nose_left_contour_4;
    private Landmark nose_left_contour_3;
    private Landmark nose_left_contour_2;
    private Landmark nose_left_contour_1;
    private Landmark nose_tip;
    private Landmark mouth_corner_right_outer;
    private Landmark mouth_lip_upper_outer_3;
    private Landmark mouth_lip_upper_outer_6;
    private Landmark mouth_lip_upper_outer_9;
    private Landmark mouth_corner_left_outer;
    private Landmark mouth_lip_lower_outer_9;
    private Landmark mouth_lip_lower_outer_6;
    private Landmark mouth_lip_lower_outer_3;
    private Landmark mouth_lip_upper_inner_3;
    private Landmark mouth_lip_upper_inner_6;
    private Landmark mouth_lip_upper_inner_9;
    private Landmark mouth_lip_lower_inner_9;
    private Landmark mouth_lip_lower_inner_6;
    private Landmark mouth_lip_lower_inner_3;
    private Landmark cheek_right_2;
    private Landmark cheek_right_4;
    private Landmark cheek_right_6;
    private Landmark cheek_right_8;
    private Landmark cheek_right_10;
    private Landmark chin_1;
    private Landmark chin_3;
    private Landmark cheek_left_10;
    private Landmark cheek_left_8;
    private Landmark cheek_left_6;
    private Landmark cheek_left_4;
    private Landmark cheek_left_2;
    private Landmark eyebrow_right_upper_1;
    private Landmark eyebrow_right_upper_5;
    private Landmark eyebrow_left_upper_1;
    private Landmark eyebrow_left_upper_5;
    private Landmark eye_right_eyelid_upper_1;
    private Landmark eye_right_eyelid_upper_3;
    private Landmark eye_right_eyelid_upper_5;
    private Landmark eye_right_eyelid_upper_7;
    private Landmark eye_right_eyelid_lower_7;
    private Landmark eye_right_eyelid_lower_5;
    private Landmark eye_right_eyelid_lower_3;
    private Landmark eye_right_eyelid_lower_1;
    private Landmark eye_right_eyeball_right;
    private Landmark eye_right_eyeball_left;
    private Landmark eye_left_eyelid_upper_1;
    private Landmark eye_left_eyelid_upper_3;
    private Landmark eye_left_eyelid_upper_5;
    private Landmark eye_left_eyelid_upper_7;
    private Landmark eye_left_eyelid_lower_7;
    private Landmark eye_left_eyelid_lower_5;
    private Landmark eye_left_eyelid_lower_3;
    private Landmark eye_left_eyelid_lower_1;
    private Landmark eye_left_eyeball_right;
    private Landmark eye_left_eyeball_left;
    private Landmark nose_bridge_1;
    private Landmark nose_bridge_2;
    private Landmark nose_bridge_3;
    private Landmark nose_right_contour_5;
    private Landmark nose_right_contour_7;
    private Landmark nose_left_contour_7;
    private Landmark nose_left_contour_5;
    private Landmark nose_middle_contour;
    private Landmark mouth_corner_right_inner;
    private Landmark mouth_corner_left_inner;
    private Landmark mouth_lip_upper_outer_1;
    private Landmark mouth_lip_upper_outer_2;
    private Landmark mouth_lip_upper_outer_4;
    private Landmark mouth_lip_upper_outer_5;
    private Landmark mouth_lip_upper_outer_7;
    private Landmark mouth_lip_upper_outer_8;
    private Landmark mouth_lip_upper_outer_10;
    private Landmark mouth_lip_upper_outer_11;
    private Landmark mouth_lip_lower_outer_11;
    private Landmark mouth_lip_lower_outer_10;
    private Landmark mouth_lip_lower_outer_8;
    private Landmark mouth_lip_lower_outer_7;
    private Landmark mouth_lip_lower_outer_5;
    private Landmark mouth_lip_lower_outer_4;
    private Landmark mouth_lip_lower_outer_2;
    private Landmark mouth_lip_lower_outer_1;
    private Landmark mouth_lip_upper_inner_1;
    private Landmark mouth_lip_upper_inner_2;
    private Landmark mouth_lip_upper_inner_4;
    private Landmark mouth_lip_upper_inner_5;
    private Landmark mouth_lip_upper_inner_7;
    private Landmark mouth_lip_upper_inner_8;
    private Landmark mouth_lip_upper_inner_10;
    private Landmark mouth_lip_upper_inner_11;
    private Landmark mouth_lip_lower_inner_11;
    private Landmark mouth_lip_lower_inner_10;
    private Landmark mouth_lip_lower_inner_8;
    private Landmark mouth_lip_lower_inner_7;
    private Landmark mouth_lip_lower_inner_5;
    private Landmark mouth_lip_lower_inner_4;
    private Landmark mouth_lip_lower_inner_2;
    private Landmark mouth_lip_lower_inner_1;

    public List<Landmark> getLandmark150List() {
        List<Landmark> list = new ArrayList<>();
        list.add(cheek_right_1);
        list.add(cheek_right_3);
        list.add(cheek_right_5);
        list.add(cheek_right_7);
        list.add(cheek_right_9);
        list.add(cheek_right_11);
        list.add(chin_2);
        list.add(cheek_left_11);
        list.add(cheek_left_9);
        list.add(cheek_left_7);
        list.add(cheek_left_5);
        list.add(cheek_left_3);
        list.add(cheek_left_1);
        list.add(eye_right_corner_right);
        list.add(eye_right_eyelid_upper_2);
        list.add(eye_right_eyelid_upper_4);
        list.add(eye_right_eyelid_upper_6);
        list.add(eye_right_corner_left);
        list.add(eye_right_eyelid_lower_6);
        list.add(eye_right_eyelid_lower_4);
        list.add(eye_right_eyelid_lower_2);
        list.add(eye_right_eyeball_center);
        list.add(eyebrow_right_corner_right);
        list.add(eyebrow_right_upper_2);
        list.add(eyebrow_right_upper_3);
        list.add(eyebrow_right_upper_4);
        list.add(eyebrow_right_corner_left);
        list.add(eyebrow_right_lower_3);
        list.add(eyebrow_right_lower_2);
        list.add(eyebrow_right_lower_1);
        list.add(eye_left_corner_right);
        list.add(eye_left_eyelid_upper_2);
        list.add(eye_left_eyelid_upper_4);
        list.add(eye_left_eyelid_upper_6);
        list.add(eye_left_corner_left);
        list.add(eye_left_eyelid_lower_6);
        list.add(eye_left_eyelid_lower_4);
        list.add(eye_left_eyelid_lower_2);
        list.add(eye_left_eyeball_center);
        list.add(eyebrow_left_corner_right);
        list.add(eyebrow_left_upper_2);
        list.add(eyebrow_left_upper_3);
        list.add(eyebrow_left_upper_4);
        list.add(eyebrow_left_corner_left);
        list.add(eyebrow_left_lower_3);
        list.add(eyebrow_left_lower_2);
        list.add(eyebrow_left_lower_1);
        list.add(nose_right_contour_1);
        list.add(nose_right_contour_2);
        list.add(nose_right_contour_3);
        list.add(nose_right_contour_4);
        list.add(nose_right_contour_6);
        list.add(nose_left_contour_6);
        list.add(nose_left_contour_4);
        list.add(nose_left_contour_3);
        list.add(nose_left_contour_2);
        list.add(nose_left_contour_1);
        list.add(nose_tip);
        list.add(mouth_corner_right_outer);
        list.add(mouth_lip_upper_outer_3);
        list.add(mouth_lip_upper_outer_6);
        list.add(mouth_lip_upper_outer_9);
        list.add(mouth_corner_left_outer);
        list.add(mouth_lip_lower_outer_9);
        list.add(mouth_lip_lower_outer_6);
        list.add(mouth_lip_lower_outer_3);
        list.add(mouth_lip_upper_inner_3);
        list.add(mouth_lip_upper_inner_6);
        list.add(mouth_lip_upper_inner_9);
        list.add(mouth_lip_lower_inner_9);
        list.add(mouth_lip_lower_inner_6);
        list.add(mouth_lip_lower_inner_3);
        list.add(cheek_right_2);
        list.add(cheek_right_4);
        list.add(cheek_right_6);
        list.add(cheek_right_8);
        list.add(cheek_right_10);
        list.add(chin_1);
        list.add(chin_3);
        list.add(cheek_left_10);
        list.add(cheek_left_8);
        list.add(cheek_left_6);
        list.add(cheek_left_4);
        list.add(cheek_left_2);
        list.add(eyebrow_right_upper_1);
        list.add(eyebrow_right_upper_5);
        list.add(eyebrow_left_upper_1);
        list.add(eyebrow_left_upper_5);
        list.add(eye_right_eyelid_upper_1);
        list.add(eye_right_eyelid_upper_3);
        list.add(eye_right_eyelid_upper_5);
        list.add(eye_right_eyelid_upper_7);
        list.add(eye_right_eyelid_lower_7);
        list.add(eye_right_eyelid_lower_5);
        list.add(eye_right_eyelid_lower_3);
        list.add(eye_right_eyelid_lower_1);
        list.add(eye_right_eyeball_right);
        list.add(eye_right_eyeball_left);
        list.add(eye_left_eyelid_upper_1);
        list.add(eye_left_eyelid_upper_3);
        list.add(eye_left_eyelid_upper_5);
        list.add(eye_left_eyelid_upper_7);
        list.add(eye_left_eyelid_lower_7);
        list.add(eye_left_eyelid_lower_5);
        list.add(eye_left_eyelid_lower_3);
        list.add(eye_left_eyelid_lower_1);
        list.add(eye_left_eyeball_right);
        list.add(eye_left_eyeball_left);
        list.add(nose_bridge_1);
        list.add(nose_bridge_2);
        list.add(nose_bridge_3);
        list.add(nose_right_contour_5);
        list.add(nose_right_contour_7);
        list.add(nose_left_contour_7);
        list.add(nose_left_contour_5);
        list.add(nose_middle_contour);
        list.add(mouth_corner_right_inner);
        list.add(mouth_corner_left_inner);
        list.add(mouth_lip_upper_outer_1);
        list.add(mouth_lip_upper_outer_2);
        list.add(mouth_lip_upper_outer_4);
        list.add(mouth_lip_upper_outer_5);
        list.add(mouth_lip_upper_outer_7);
        list.add(mouth_lip_upper_outer_8);
        list.add(mouth_lip_upper_outer_10);
        list.add(mouth_lip_upper_outer_11);
        list.add(mouth_lip_lower_outer_11);
        list.add(mouth_lip_lower_outer_10);
        list.add(mouth_lip_lower_outer_8);
        list.add(mouth_lip_lower_outer_7);
        list.add(mouth_lip_lower_outer_5);
        list.add(mouth_lip_lower_outer_4);
        list.add(mouth_lip_lower_outer_2);
        list.add(mouth_lip_lower_outer_1);
        list.add(mouth_lip_upper_inner_1);
        list.add(mouth_lip_upper_inner_2);
        list.add(mouth_lip_upper_inner_4);
        list.add(mouth_lip_upper_inner_5);
        list.add(mouth_lip_upper_inner_7);
        list.add(mouth_lip_upper_inner_8);
        list.add(mouth_lip_upper_inner_10);
        list.add(mouth_lip_upper_inner_11);
        list.add(mouth_lip_lower_inner_11);
        list.add(mouth_lip_lower_inner_10);
        list.add(mouth_lip_lower_inner_8);
        list.add(mouth_lip_lower_inner_7);
        list.add(mouth_lip_lower_inner_5);
        list.add(mouth_lip_lower_inner_4);
        list.add(mouth_lip_lower_inner_2);
        list.add(mouth_lip_lower_inner_1);
        return list;
    }
}
